/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.ClientController;
import domain.Kupac;
import domain.PreferencijaKupca;
import domain.Sladoled;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Vukos
 */
public class PreferencijaKupcaForm extends javax.swing.JDialog {

    private Kupac kupac;
    private Sladoled sladoled;

    /**
     * Creates new form PreferencijaKupca
     */
    public PreferencijaKupcaForm(java.awt.Frame parent, boolean modal, Kupac k, Sladoled s) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Preferencije kupca");
        kupac = k;
        sladoled = s;
        lblSlad.setText("Sladoled: '" + sladoled.getNazivSladoleda() + "'");
        lblKup.setText("Kupac: " + kupac.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOcena = new javax.swing.JTextField();
        lblKupac = new javax.swing.JLabel();
        lblSladoled = new javax.swing.JLabel();
        btnOceni = new javax.swing.JButton();
        lblSlad = new javax.swing.JLabel();
        lblKup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOceni.setText("Oceni");
        btnOceni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOceniActionPerformed(evt);
            }
        });

        lblSlad.setText("jLabel2");

        lblKup.setText("jLabel2");

        jLabel1.setText("Ocena:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSlad)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(lblKupac)
                                .addGap(65, 65, 65)
                                .addComponent(lblSladoled))
                            .addComponent(lblKup)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOceni)
                            .addComponent(txtOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKupac)
                    .addComponent(lblSladoled))
                .addGap(17, 17, 17)
                .addComponent(lblKup)
                .addGap(18, 18, 18)
                .addComponent(lblSlad)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addComponent(btnOceni)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOceniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOceniActionPerformed
        // TODO add your handling code here:
        if (txtOcena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti ocenu.");
            return;
        }
        String oc = txtOcena.getText();
        String[] ocene = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};
        boolean da = false;
        for (String o : ocene) {
            if (oc.equals(o)) {
                da = true;
            }
        }
        if (!da) {
            JOptionPane.showMessageDialog(this, "Morate uneti ocenu u rasponu od 1 do 10.");
            return;
        }

        int ocena = Integer.parseInt(txtOcena.getText());
        PreferencijaKupca pk = new PreferencijaKupca(ocena, kupac, sladoled);

        try {
            ClientController.getInstance().addPreferencija(pk);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao preferenciju kupca!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnOceniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOceni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblKup;
    private javax.swing.JLabel lblKupac;
    private javax.swing.JLabel lblSlad;
    private javax.swing.JLabel lblSladoled;
    private javax.swing.JTextField txtOcena;
    // End of variables declaration//GEN-END:variables
}
